
# Variáveis
# $_DOCKERFILE
#   Esta variável precisa ser criada nas configurações do acionador do google cloud
#   com o caminho para o arquivo dockerfile específico daquele acionador.
#   Ex.: _DOCKERFILE=./Dockerfile.staging
#   Dentro deste dockerfile é necessário que as variáveis de ambiente corretas estejam
#   definidas para o correto funcionamento do sistema.
#   Para cadastrar essa variável, vá ao menu CLoud Build, depois em Acionadores no menu
#   lateral. Localize o acionador que será modificado e clique no final na opção "editar"    

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/klawdyo-awesome-project/$REPO_NAME:$SHORT_SHA', '--file=$_DOCKERFILE', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/klawdyo-awesome-project/$REPO_NAME:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '$_SERVICE_NAME', '--region=$_DEPLOY_REGION', '--platform=$_PLATFORM', '--image=gcr.io/klawdyo-awesome-project/$REPO_NAME:$SHORT_SHA']

# gcloud beta run deploy klawdyo-awesome-project --region=us-central1  --platform=managed --image=gcr.io/klawdyo-awesome-project/klawdyo-awesome-project:d43b044
  # env:
  # - 'CAND_ENV=staging'
  # - 'ADMIN_URL=https://staging.candidapp.com.br'
  # - 'API_URL=https://staging.api.candidapp.com.br'
