steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/klawdyo-awesome-project/klawdyo-awesome-project:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/klawdyo-awesome-project/klawdyo-awesome-project:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'klawdyo-awesome-project', '--region=us-central1', '--platform=managed', '--image=gcr.io/klawdyo-awesome-project/klawdyo-awesome-project:$SHORT_SHA']


# gcloud beta run deploy klawdyo-awesome-project --region=us-central1  --platform=managed --image=gcr.io/klawdyo-awesome-project/klawdyo-awesome-project:d43b044
