steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/klawdyo-awesome-project/$REPO_NAME:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/klawdyo-awesome-project/$REPO_NAME:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '$_SERVICE_NAME', '--region=$_DEPLOY_REGION', '--platform=$_PLATFORM', '--image=gcr.io/klawdyo-awesome-project/$REPO_NAME:$SHORT_SHA']
  env:
  - 'CAND_ENV=staging'
  - 'ADMIN_URL=https://staging.candidapp.com.br'
  - 'API_URL=https://staging.api.candidapp.com.br'

# gcloud beta run deploy klawdyo-awesome-project --region=us-central1  --platform=managed --image=gcr.io/klawdyo-awesome-project/klawdyo-awesome-project:d43b044
