steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/klawdyo-awesome-project/klawdyo-awesome-project:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/klawdyo-awesome-project/klawdyo-awesome-project:$SHORT_SHA']
