FROM node:13-slim
WORKDIR /app
ADD . /app

# Variáveis de ambiente específicas para o ambuente do projeto
ENV CAND_ENV=staging
ENV CAND_ADMIN=https://staging.candidapp.com.br
ENV CAND_API=https://staging.api.candidapp.com.br

CMD node server.js
