FROM node:13-slim
WORKDIR /app
ADD . /app

# Variáveis de ambiente específicas para o ambuente do projeto
ENV CAND_ENV=production
ENV CAND_ADMIN=https://candidapp.com.br
ENV CAND_API=https://api.candidapp.com.br

CMD node server.js
